[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = eAb3HiSf3TGdF0VScN3btH4wHlsehZfjRowD9PBj/WI=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
